version: '3.8'

services:
  
  db-mysql:
    image: mysql:8.0.33
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin      
      MYSQL_USER: ilima
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - florescer
  
  #jenkins:
    #image: jenkins/jenkins:2.414.1-lts-jdk17
    #container_name: jenkins
    #ports:
      #- 9090:8080
      #- 8080:8081
    #networks:
      #- florescer  
    #volumes:
      #- jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  florescer:
    internal:
      false
      
  #api-florescer:
    #build:
     #context: .
     #dockerfile: Dockerfile-DEV
    #image: ilimafilho/florescer:1.0.0
    #restart: unless-stopped
    #environment:
      #MYSQL_HOST: db-mysql:3306
    #ports:
      #- 8080:8080
    #depends_on:
      #- db-mysql  
    #networks:
      #- florescer  
  
  #rabbitmq:
    #image: rabbitmq:3.10-management
    #container_name: rabbitmq
    #restart: unless-stopped
    #ports:
      #- 5672:5672
      #- 15672:15672
    #volumes:
      #- ./dados:/var/lib/rabbitmq/
    #environment:
      #- RABBITMQ_DEFAULT_USER=ilima
      #- RABBITMQ_DEFAULT_PASS=admin      