apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-florescer-deployment
spec:
  template:
    metadata:
      name: db-florescer
      labels:
        app: db-florescer
    spec:
      containers:
        - name: db-florescer-container
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-florescer